export const PermissionsLists = [
    // Dashboard
    {
        key: 'dashboard-list',
        group: 'dashboard',
        type: 'list',
        title: 'Dashboard List',
        order: 1,
        category: 'dashboard',
    },
    {
        key: 'dashboard-create',
        group: 'dashboard',
        type: 'create',
        title: 'Dashboard Create',
        order: 1,
        category: 'dashboard',
    },
    {
        key: 'dashboard-update',
        group: 'dashboard',
        type: 'update',
        title: 'Dashboard Update',
        order: 1,
        category: 'dashboard',
    },
    {
        key: 'dashboard-delete',
        group: 'dashboard',
        type: 'delete',
        title: 'Dashboard Delete',
        order: 1,
        category: 'dashboard',
    },

    // Users
    {
        key: 'users-list',
        group: 'users',
        type: 'list',
        title: 'Users List',
        order: 2,
        category: 'users',
    },
    {
        key: 'users-create',
        group: 'users',
        type: 'create',
        title: 'Users Create',
        order: 2,
        category: 'users',
    },
    {
        key: 'users-update',
        group: 'users',
        type: 'update',
        title: 'Users Update',
        order: 2,
        category: 'users',
    },
    {
        key: 'users-delete',
        group: 'users',
        type: 'delete',
        title: 'Users Delete',
        order: 2,
        category: 'users',
    },

    // Chapters
    {
        key: 'chapters-list',
        group: 'chapters',
        type: 'list',
        title: 'Chapters List',
        order: 3,
        category: 'chapters',
    },
    {
        key: 'chapters-create',
        group: 'chapters',
        type: 'create',
        title: 'Chapters Create',
        order: 3,
        category: 'chapters',
    },
    {
        key: 'chapters-update',
        group: 'chapters',
        type: 'update',
        title: 'Chapters Update',
        order: 3,
        category: 'chapters',
    },
    {
        key: 'chapters-delete',
        group: 'chapters',
        type: 'delete',
        title: 'Chapters Delete',
        order: 3,
        category: 'chapters',
    },

    // Performers
    {
        key: 'performers-list',
        group: 'performers',
        type: 'list',
        title: 'Performers List',
        order: 4,
        category: 'performers',
    },
    {
        key: 'performers-create',
        group: 'performers',
        type: 'create',
        title: 'Performers Create',
        order: 4,
        category: 'performers',
    },
    {
        key: 'performers-update',
        group: 'performers',
        type: 'update',
        title: 'Performers Update',
        order: 4,
        category: 'performers',
    },
    {
        key: 'performers-delete',
        group: 'performers',
        type: 'delete',
        title: 'Performers Delete',
        order: 4,
        category: 'performers',
    },

    // Associates
    {
        key: 'associates-list',
        group: 'associates',
        type: 'list',
        title: 'Associates List',
        order: 5,
        category: 'associates',
    },
    {
        key: 'associates-create',
        group: 'associates',
        type: 'create',
        title: 'Associates Create',
        order: 5,
        category: 'associates',
    },
    {
        key: 'associates-update',
        group: 'associates',
        type: 'update',
        title: 'Associates Update',
        order: 5,
        category: 'associates',
    },
    {
        key: 'associates-delete',
        group: 'associates',
        type: 'delete',
        title: 'Associates Delete',
        order: 5,
        category: 'associates',
    },

    // Enquiries
    {
        key: 'enquiries-list',
        group: 'enquiries',
        type: 'list',
        title: 'Enquiries List',
        order: 6,
        category: 'enquiries',
    },
    {
        key: 'enquiries-create',
        group: 'enquiries',
        type: 'create',
        title: 'Enquiries Create',
        order: 6,
        category: 'enquiries',
    },
    {
        key: 'enquiries-update',
        group: 'enquiries',
        type: 'update',
        title: 'Enquiries Update',
        order: 6,
        category: 'enquiries',
    },
    {
        key: 'enquiries-delete',
        group: 'enquiries',
        type: 'delete',
        title: 'Enquiries Delete',
        order: 6,
        category: 'enquiries',
    },

    // Payments
    {
        key: 'payments-list',
        group: 'payments',
        type: 'list',
        title: 'Payments List',
        order: 7,
        category: 'payments',
    },
    {
        key: 'payments-create',
        group: 'payments',
        type: 'create',
        title: 'Payments Create',
        order: 7,
        category: 'payments',
    },
    {
        key: 'payments-update',
        group: 'payments',
        type: 'update',
        title: 'Payments Update',
        order: 7,
        category: 'payments',
    },
    {
        key: 'payments-delete',
        group: 'payments',
        type: 'delete',
        title: 'Payments Delete',
        order: 7,
        category: 'payments',
    }
];
